[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

[plugins]
  package = "@netlify/plugin-nextjs"

# Set Node.js version compatible with Next.js 14
[build.environment]
  NODE_VERSION = "18"
